# src/main/resources/application.yml

server:
  port: 8082  # Change to your desired port number

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active:
      - "qa"

build:
  version: "3.0"


cards:
  message: "Welcome to MicroFin-Suite cards related local APIs "
  contactDetails:
    name: "Mohamed Tamer"
    email: "mohamedtamerdev@gmail.com"
  onCallSupport:
    - +201159749780
    - +201032105166