services:
  accounts:
    image: "mohamedtamer0/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - mohamedtamer0
  loans:
    image: "mohamedtamer0/loans:s4"
    container_name: loans-ms
    ports:
      - "8083:8083"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - mohamedtamer0
  cards:
    image: "mohamedtamer0/cards:s4"
    container_name: cards-ms
    ports:
      - "8082:8082"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - mohamedtamer0
networks:
  mohamedtamer0:
    driver: "bridge"