spring:
  application:
    name: "configserver"
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
        # search-locations: "classpath:/config"
        git:
          uri: "https://github.com/mohamedtamer0/MicroFin-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8084